import Link from 'next/link'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Header from '../../components/Header';
import Footer from '../../components/Footer';

export default function Mint() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>バースデーカードNFT発行システム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </div>
    </>
  )
}