import Link from 'next/link'
import Head from 'next/head'
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';

export default function Mint() {
  return (
    <>
    <div>
      <Head>
        <title>バースデーカードNFT発行システム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className='flex justify-center p-3'>
        <button className="bg-transparent hover:bg-orange-600 text-orange-500 font-semibold hover:text-white py-2 px-4 border border-orange-500 hover:border-transparent rounded">
          NFTを発行する
        </button>
      </main>
      <Footer />
    </div>
    </>
  )
}