import Link from 'next/link'
import Head from 'next/head'
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { useState } from 'react';
import { useEffect } from 'react';
import Web3 from 'react';

export default function Mint() {
  
  const [wallet,setWalletAddress] = useState(null)
  
  const connectWallet = async () => {
    // Check if MetaMask is installed on user's browser
    if(window.ethereum) {
      const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
      const chainId = await window.ethereum.request({ method: 'eth_chainId'});
      // Check if user is connected to Ropsten
      if(chainId != '0x3') {
        alert("Please connect to Ropsten");
      } else {
        let wallet = accounts[0];
        setWalletAddress(wallet);
        mintNFT();
      }
    } else {
      alert("Please install Mask");
    }
  }

  const mintNFT = async () => {
    const Web3 = require('web3');
    const web3 = new Web3(window.ethereum);
    await window.ethereum.enable();
    const contract_abi = require('../../../abi/abi.json');
    const contract_address = '0xdab6dAC596529D64e015EFb40f51aaf5eF5f38Ee';
    const MintContract = new web3.eth.Contract(contract_abi, contract_address);
    MintContract.methods.mintBirthCard("0xC81D5a4c75636F05F559a0e7bA4ca643D94858ed","ipfs://QmPpjH7tRQU5gwiu7NJYz862E8cBF4ZhKDWRbiWf4nYmT4").send();
  }

  return (
    <>
    <div>
      <Head>
        <title>バースデーカードNFT発行システム</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className='flex justify-center p-3'>
        <button className="bg-transparent hover:bg-orange-600 text-orange-500 font-semibold hover:text-white py-2 px-4 border border-orange-500 hover:border-transparent rounded" onClick={connectWallet}>
          NFTを発行する
        </button>
      </main>
      <Footer />
    </div>
    </>
  )
}